### ISSUE TITLE
Design Methodology

### ISSUE THREAD

**Issue by agneym** [Coronasafe/02-journal#3]
Currently, the Merchant has parameters - Name, Mobile Number, Address, District, Local Body Type and Local Body. When this switches over to 0₂ cylinders, what are the changes you would like to see here? 

Name = Serial number
Address = ?
District, Local Body = ?
Mobile Number = ?

User has params - Name, Mobile number, Date of Birth 
When we switch it over to government officials, I'm assuming that you still need 

Name = official name
Mobile number = official number (may be not, but this is how journal works.)
date of birth = ? (nah!)
Something to identify filling station = ? 
Location of filling station = port over the district, local body fields from merchant?

**Comment by bodhish** [comment]
Admin should be able to generate QR code for each cylinder.

It should have a flag full, empty

It should have an option to be marked as faulty


Any vendor / offical can be registered, they can generate n number of QR code for a cylinder. 

Also keep fields that you see as required

**Comment by agneym** [comment]
## Terminology: 

* Station: A physical place where cylinders are currently stored. Admin can add, edit or remove these locations.
* User: User can scan an oxygen cylinder and update it's status
* Supplier: Oxygen cylinder supplier, they can generate QR codes for n number of cylinders. 

## Workflow

### Supplier side

* Supplier enters their information on `/supplier` and downloads QR codes for their cylinders.

### User side

* Admin adds stations 
* User signs up and selects a station they operate under.
* User can scan a cylinder QR code and update it's status

### Admin side 

* Admin can view, create and delete stations. 
* Admin can search cylinders via their supplier name 
* Admin can view cylinder concentration via locality
* Admin can view current cylinder status of a station

**Comment by agneym** [comment]
Moving to https://github.com/coronasafe/02-journal/discussions/19#discussion-3366825
